// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvO6I07btKjeau4MruiHfboWYlSOtuqI',
    appId: '1:220235108886:web:80c235421d2417c04c9b37',
    messagingSenderId: '220235108886',
    projectId: 'tempatwisata-2bba1',
    authDomain: 'tempatwisata-2bba1.firebaseapp.com',
    databaseURL: 'https://tempatwisata-2bba1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tempatwisata-2bba1.firebasestorage.app',
    measurementId: 'G-D79K21123D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxoPmq2RJjABfSWf5Y6_RDvVIW2FIBOk',
    appId: '1:220235108886:android:5bf874c62ff72ec14c9b37',
    messagingSenderId: '220235108886',
    projectId: 'tempatwisata-2bba1',
    databaseURL: 'https://tempatwisata-2bba1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tempatwisata-2bba1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQvO6I07btKjeau4MruiHfboWYlSOtuqI',
    appId: '1:220235108886:web:3e5862b16cd5f2af4c9b37',
    messagingSenderId: '220235108886',
    projectId: 'tempatwisata-2bba1',
    authDomain: 'tempatwisata-2bba1.firebaseapp.com',
    databaseURL: 'https://tempatwisata-2bba1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tempatwisata-2bba1.firebasestorage.app',
    measurementId: 'G-LXM0DE4N1P',
  );
}
